version: "3.8"

services:
  artisan:
    tty: true
    build: .
    depends_on:
      - db
    ports:
      - '8000:8000'
  db:
    image: postgres:14.5-alpine3.16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'